/**
 * MCP_Server: Clear Skies/Rough Air - Core Server Logic (TypeScript/Node.js)
 * Enhanced to accept API keys for Weather, Flight Data, and News.
 * Includes robust fetch with retries, NOAA METAR usage, and sane fallbacks.
 *
 * Requirements:
 * - Node 18+ (global fetch + AbortController)
 * - dotenv for environment variables
 */

import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
// Load environment variables from .env file
import * as dotenv from 'dotenv';
dotenv.config();


// ---------------------------------------------------


async function testAPIKeys() {
  console.log('\n🧪 Testing Individual API Keys...\n');
  
  // Test AviationStack with correct parameters
  try {
    console.log('Testing AviationStack API...');
    const flightUrl = `https://api.aviationstack.com/v1/flights?access_key=${process.env.AVIATIONSTACK_API_KEY}&airline_iata=AA&limit=5`;
    const flightResponse = await fetch(flightUrl);
    console.log(`✅ AviationStack: ${flightResponse.status} ${flightResponse.statusText}`);
    if (!flightResponse.ok) {
      const errorText = await flightResponse.text();
      console.log(`❌ AviationStack Error: ${errorText}`);
    } else {
      const data = await flightResponse.json();
      if (data.error) {
        console.log(`❌ AviationStack API Error: ${data.error.message}`);
      } else {
        console.log(`✅ Found ${data?.data?.length || 0} flights for American Airlines`);
      }
    }
  } catch (error) {
    console.log(`❌ AviationStack Failed: ${error}`);
  }

  // Test NewsData.io
  try {
    console.log('Testing NewsData.io API...');
    const newsUrl = `https://newsdata.io/api/1/news?apikey=${process.env.NEWSDATA_API_KEY}&q=airline&country=us&size=1`;
    const newsResponse = await fetch(newsUrl);
    console.log(`✅ NewsData.io: ${newsResponse.status} ${newsResponse.statusText}`);
    if (!newsResponse.ok) {
      const errorText = await newsResponse.text();
      console.log(`❌ NewsData.io Error: ${errorText}`);
    }
  } catch (error) {
    console.log(`❌ NewsData.io Failed: ${error}`);
  }

  // Test WeatherAPI
  try {
    console.log('Testing WeatherAPI.com...');
    const weatherUrl = `https://api.weatherapi.com/v1/current.json?key=${process.env.WEATHER_API_KEY}&q=JFK`;
    const weatherResponse = await fetch(weatherUrl);
    console.log(`✅ WeatherAPI.com: ${weatherResponse.status} ${weatherResponse.statusText}`);
    if (!weatherResponse.ok) {
      const errorText = await weatherResponse.text();
      console.log(`❌ WeatherAPI.com Error: ${errorText}`);
    } else {
      console.log(`✅ Weather API working - got data for JFK`);
    }
  } catch (error) {
    console.log(`❌ WeatherAPI.com Failed: ${error}`);
  }
  
  console.log('\n');
}

async function testDifferentQueries() {
  console.log('\n🎯 Testing Single Query to Save API Calls...\n');
  
  // Single test with a common American Airlines flight
  console.log('=== Single Test: American Airlines ===');
  await mcpServer.processQuery('Check AA1052 status today. Any delays or cancellations?');
  
  console.log('\n🎯 Single test complete! Check above for flight matching results.');
}

// -------------------- 0. Config --------------------

type MCPConfig = {
  WEATHER_API_KEY: string;
  AVIATIONSTACK_API_KEY: string;
  NEWSDATA_API_KEY: string;
  TSA_API_KEY: string;
  GEMINI_API_KEY: string;
  SIMULATION: boolean; // if true (default), mocks fill any missing pieces
  REQUEST_TIMEOUT_MS: number;
  MAX_RETRIES: number;
};

const DefaultConfig: MCPConfig = {
  WEATHER_API_KEY: process.env.WEATHER_API_KEY || '',
  AVIATIONSTACK_API_KEY: process.env.AVIATIONSTACK_API_KEY || '',
  NEWSDATA_API_KEY: process.env.NEWSDATA_API_KEY || '',
  TSA_API_KEY: process.env.TSA_API_KEY || 'https://apps.tsa.dhs.gov/MyTSAWebService/GetConfirmedWaitTimes.ashx',
  GEMINI_API_KEY: process.env.GEMINI_API_KEY || '',
  SIMULATION: process.env.SIMULATION ? process.env.SIMULATION !== 'false' : false,  // Changed default to false
  REQUEST_TIMEOUT_MS: parseInt(process.env.REQUEST_TIMEOUT_MS || '8000', 10),
  MAX_RETRIES: parseInt(process.env.MAX_RETRIES || '2', 10),
};

// -------------------- 1. Core Data Structures --------------------

// Structured Intent generated by the Gemini Prompt Gateway
interface TravelIntent {
  id: string; // Unique query ID
  action: 'risk_check' | 'resilience_check' | 'rebook_options';
  flightDesignator?: string; // e.g., 'AA123'
  originAirport?: string; // e.g., 'JFK'
  destinationAirport?: string; // e.g., 'LAX'
  dateOfTravel: string; // YYYY-MM-DD
  riskThreshold: number; // 0.0 to 1.0, used for auto-triggers
  requestedBackups: string[]; // e.g., ['hotel', 'rebooking', 'car']
}

// Fused Data Structure
interface FusedData {
  flight: {
    status: 'On Time' | 'Delayed' | 'Cancelled' | 'Scheduled';
    inboundTailDelayMinutes: number; // Proxy for mechanical/ops risk
    aircraftAgeYears: number; // Proxy for maintenance risk
  };
  weather: {
    enrouteConvectiveRisk: 'Low' | 'Moderate' | 'High';
    metar: string; // Actual weather report text
  };
  tsa: {
    waitMinutes: number;
    isAboveBaseline: boolean;
  };
  context: {
    strikeRisk: boolean; // News/labor action data
    advisories: string[]; // Passport/Visa/Health alerts
    atcProgram: boolean; // FAA GDP/EDCT advisory active
  };
}

// Add this interface after the existing FusedData interface
interface DataSource {
  source: string;
  apiUsed: boolean;
  success: boolean;
  timestamp: string;
  rawData?: any;
  errorMessage?: string;
}

interface EnhancedFusedData extends FusedData {
  dataSources: {
    flight: DataSource;
    weather: DataSource;
    news: DataSource;
    tsa: DataSource;
  };
}

// -------------------- 2. Utilities --------------------

function sleep(ms: number) {
  return new Promise((res) => setTimeout(res, ms));
}

async function fetchWithRetry(
  url: string,
  options: RequestInit,
  cfg: MCPConfig,
  acceptableStatus: number[] = [200]
): Promise<Response> {
  let attempt = 0;
  const maxAttempts = cfg.MAX_RETRIES + 1;
  let lastError: unknown;

  while (attempt < maxAttempts) {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), cfg.REQUEST_TIMEOUT_MS);

    try {
      const res = await fetch(url, { ...options, signal: controller.signal });
      clearTimeout(timeout);

      if (acceptableStatus.includes(res.status)) {
        return res;
      }

      // Retry on 429/5xx
      if (res.status === 429 || (res.status >= 500 && res.status < 600)) {
        attempt++;
        const backoff = Math.min(1000 * Math.pow(2, attempt) + Math.random() * 200, 8000);
        await sleep(backoff);
        continue;
      }

      // For other non-OK, stop and throw
      throw new Error(`HTTP ${res.status} for ${url}`);
    } catch (err) {
      clearTimeout(timeout);
      lastError = err;
      attempt++;
      if (attempt >= maxAttempts) break;
      const backoff = Math.min(1000 * Math.pow(2, attempt) + Math.random() * 200, 8000);
      await sleep(backoff);
    }
  }

  throw lastError instanceof Error ? lastError : new Error('Unknown fetch error');
}

function toISODate(date: Date): string {
  const y = date.getFullYear();
  const m = (date.getMonth() + 1).toString().padStart(2, '0');
  const d = date.getDate().toString().padStart(2, '0');
  return `${y}-${m}-${d}`;
}

function inferDateFromPrompt(prompt: string): string {
  const p = prompt.toLowerCase();
  const today = new Date();
  if (p.includes('tomorrow')) {
    const dt = new Date(today);
    dt.setDate(today.getDate() + 1);
    return toISODate(dt);
  }
  if (p.includes('today')) {
    return toISODate(today);
  }
  // Fallback: tomorrow
  const dt = new Date(today);
  dt.setDate(today.getDate() + 1);
  return toISODate(dt);
}

function parseFlightDesignator(prompt: string): string | undefined {
  // Simple AA123 / DL4567 finder: two letters + 1-4 digits
  const m = prompt.toUpperCase().match(/\b([A-Z]{2}\d{1,4})\b/);
  return m ? m[1] : undefined;
}

function parseIataPair(prompt: string): { origin?: string; destination?: string } {
  // Simple IATA finder by common phrase patterns: "ORD to MIA", "JFK-LAX"
  const m1 = prompt.toUpperCase().match(/\b([A-Z]{3})\s*(?:-|to|→|->)\s*([A-Z]{3})\b/);
  if (m1) return { origin: m1[1], destination: m1[2] };
  return {};
}

function toICAO(iata?: string): string | undefined {
  if (!iata || iata.length !== 3) return undefined;
  // Basic US mapping: 'K' + IATA. Works for major US airports (JFK -> KJFK).
  return `K${iata.toUpperCase()}`;
}

function riskFromMetar(metar: string): 'Low' | 'Moderate' | 'High' {
  const M = metar.toUpperCase();
  if (!M) return 'Low';
  if (M.includes(' TS ') || M.includes('TSRA') || M.includes(' TSGR ') || M.includes(' CB ') || M.includes(' +TS')) {
    return 'High';
  }
  if (M.includes('SHRA') || M.includes('RA') || M.includes('OVC') || M.includes('BKN')) {
    return 'Moderate';
  }
  return 'Low';
}

// -------------------- 3. Provider Adapters --------------------

// Weather adapter:
// - METAR via NOAA (no key) for `metar` and convective inference.
// - Optional WeatherAPI.com (if WEATHER_API_KEY provided) to augment risk (kept simple here).
// Enhanced Weather adapter with detailed logging
class WeatherAdapter {
  constructor(private cfg: MCPConfig) {}

  private async getMetarNOAA(icao?: string): Promise<{ metar: string; source: DataSource }> {
    const source: DataSource = {
      source: 'NOAA METAR',
      apiUsed: false,
      success: false,
      timestamp: new Date().toISOString()
    };

    if (!icao || icao.length !== 4) {
      source.errorMessage = 'Invalid ICAO code';
      return { metar: '', source };
    }

    const url = `https://tgftp.nws.noaa.gov/data/observations/metar/stations/${icao}.TXT`;
    source.apiUsed = true;
    
    try {
      console.log(`[Weather API] Calling NOAA METAR: ${url}`);
      const res = await fetchWithRetry(url, { method: 'GET' }, this.cfg, [200, 404]);
      
      if (res.status === 404) {
        source.success = false;
        source.errorMessage = 'METAR not found for airport';
        console.log(`[Weather API] METAR not found for ${icao}`);
        return { metar: '', source };
      }
      
      const txt = await res.text();
      const lines = txt.trim().split('\n');
      const metar = lines.length > 1 ? lines[1].trim() : lines[0]?.trim() ?? '';
      
      source.success = true;
      source.rawData = { fullResponse: txt, extractedMETAR: metar };
      console.log(`[Weather API] SUCCESS - METAR retrieved: ${metar.substring(0, 50)}...`);
      
      return { metar, source };
    } catch (error) {
      source.success = false;
      source.errorMessage = error instanceof Error ? error.message : 'Unknown error';
      console.log(`[Weather API] FAILED - ${source.errorMessage}`);
      return { metar: '', source };
    }
  }

  private async refineRiskWithWeatherAPI(iata?: string, current: 'Low' | 'Moderate' | 'High' = 'Low'): Promise<{
    risk: 'Low' | 'Moderate' | 'High';
    weatherApiData?: any;
  }> {
    if (!this.cfg.WEATHER_API_KEY || !iata) {
      console.log(`[Weather API] WeatherAPI.com skipped - ${!this.cfg.WEATHER_API_KEY ? 'No API key' : 'No IATA code'}`);
      return { risk: current };
    }
    
    const url = `https://api.weatherapi.com/v1/current.json?key=${this.cfg.WEATHER_API_KEY}&q=${encodeURIComponent(iata)}`;
    
    try {
      console.log(`[Weather API] Calling WeatherAPI.com for ${iata}`);
      const res = await fetchWithRetry(url, { method: 'GET' }, this.cfg);
      const data = await res.json();
      
      console.log(`[Weather API] WeatherAPI.com SUCCESS - Current: ${data?.current?.condition?.text}, Temp: ${data?.current?.temp_f}°F`);
      
      const cond: string = data?.current?.condition?.text?.toLowerCase?.() || '';
      let risk = current;
      if (cond.includes('thunder')) risk = 'High';
      else if (cond.includes('rain') || cond.includes('showers')) risk = current === 'Low' ? 'Moderate' : current;
      
      return { risk, weatherApiData: data?.current };
    } catch (error) {
      console.log(`[Weather API] WeatherAPI.com FAILED - ${error}`);
      return { risk: current };
    }
  }

  public async get(airportIata?: string): Promise<{ 
    metar: string; 
    enrouteConvectiveRisk: 'Low' | 'Moderate' | 'High';
    source: DataSource;
  }> {
    const icao = toICAO(airportIata);
    console.log(`[Weather API] Getting weather for ${airportIata} (ICAO: ${icao})`);
    
    const { metar, source } = await this.getMetarNOAA(icao);
    let risk = riskFromMetar(metar);
    
    const { risk: refinedRisk, weatherApiData } = await this.refineRiskWithWeatherAPI(airportIata, risk);
    
    // Enhance source with WeatherAPI data if available
    if (weatherApiData) {
      source.rawData = { ...source.rawData, weatherApiData };
    }
    
    console.log(`[Weather API] Final risk assessment: ${refinedRisk} (METAR-based: ${risk})`);
    
    return { 
      metar: metar || `METAR ${airportIata || 'N/A'}: (not available)`, 
      enrouteConvectiveRisk: refinedRisk,
      source 
    };
  }
}

// Flight adapter (Aviationstack if key present; fallback to mock)
type FlightProbe = {
  status: 'On Time' | 'Delayed' | 'Cancelled' | 'Scheduled';
  inboundTailDelayMinutes: number;
  aircraftAgeYears: number;
  origin?: string;
  destination?: string;
};

// Enhanced Flight adapter with better matching logic and debugging
class FlightAdapter {
  private cfg: MCPConfig;
  
  constructor(cfg: MCPConfig) {
    this.cfg = cfg;
  }

  private parseFlightDesignator(flight: string): { airlineCode?: string; flightNumber?: string } {
    const match = flight.toUpperCase().match(/^([A-Z]{2})(\d{1,4})$/);
    if (match) {
      return {
        airlineCode: match[1],
        flightNumber: match[2]
      };
    }
    return {};
  }

  public async getByDesignator(flight: string, dateISO: string): Promise<FlightProbe & { source: DataSource }> {
    const source: DataSource = {
      source: 'AviationStack',
      apiUsed: false,
      success: false,
      timestamp: new Date().toISOString()
    };

    if (!this.cfg.AVIATIONSTACK_API_KEY || this.cfg.SIMULATION) {
      source.source = 'Mock Data (Simulation)';
      source.success = true;
      source.errorMessage = this.cfg.SIMULATION ? 'Simulation mode enabled' : 'No API key provided';
      
      const mockData = {
        status: 'Scheduled' as const,
        inboundTailDelayMinutes: flight.toUpperCase().includes('AA123') ? 45 : 10,
        aircraftAgeYears: flight.toUpperCase().includes('AA123') ? 18 : 7,
        origin: flight.toUpperCase().includes('AA') ? 'JFK' : 'ORD',
        destination: flight.toUpperCase().includes('AA') ? 'LAX' : 'MIA',
      };
      
      console.log(`[Flight API] Using MOCK data for ${flight}: Status=${mockData.status}, Delay=${mockData.inboundTailDelayMinutes}m`);
      source.rawData = mockData;
      
      return { ...mockData, source };
    }

    const { airlineCode, flightNumber } = this.parseFlightDesignator(flight);
    if (!airlineCode || !flightNumber) {
      source.success = false;
      source.errorMessage = 'Invalid flight format. Expected format: AA123';
      console.log(`[Flight API] Invalid flight format: ${flight}`);
      
      const fallbackData = {
        status: 'Scheduled' as const,
        inboundTailDelayMinutes: 10,
        aircraftAgeYears: 8,
      };
      return { ...fallbackData, source };
    }

      // In your FlightAdapter, replace the queryStrategies with:
    const queryStrategies = [
      {
        name: 'Direct Flight Search', 
        params: {
          access_key: this.cfg.AVIATIONSTACK_API_KEY,
          flight_iata: flight.toUpperCase(),
          limit: '10'
        }
      },
      {
        name: 'Airline Recent Flights',
        params: {
          access_key: this.cfg.AVIATIONSTACK_API_KEY,
          airline_iata: airlineCode, 
          limit: '50'
        }
      },
      {
        name: 'Today\'s Flights by Airline',
        params: {
          access_key: this.cfg.AVIATIONSTACK_API_KEY,
          airline_iata: airlineCode,
          flight_date: new Date().toISOString().split('T')[0], // 2025-01-08
          limit: '100'
        }
      }
    ];

    source.apiUsed = true;

    for (let i = 0; i < queryStrategies.length; i++) {
      const strategy = queryStrategies[i];
      
      const url = 'https://api.aviationstack.com/v1/flights?' + 
        Object.entries(strategy.params)
          .map(([key, value]) => `${key}=${encodeURIComponent(value)}`)
          .join('&');

      try {
        console.log(`[Flight API] Strategy ${i + 1}/${queryStrategies.length}: ${strategy.name}`);
        console.log(`[Flight API] Looking for flight: ${flight} (airline: ${airlineCode}, number: ${flightNumber})`);
        
        const res = await fetchWithRetry(url, { method: 'GET' }, this.cfg);
        const json: any = await res.json();
        
        if (json.error) {
          console.log(`[Flight API] API Error: ${json.error.message || 'Unknown error'}`);
          continue;
        }
        
        source.rawData = json;
        const flights = json?.data || [];
        console.log(`[Flight API] Found ${flights.length} total flights for ${airlineCode}`);
        
        if (flights.length === 0) {
          continue;
        }
        
        // 🔧 ENHANCED MATCHING LOGIC
        console.log(`[Flight API] 🔍 Analyzing first 5 flights for matching patterns:`);
        flights.slice(0, 5).forEach((f: any, idx: number) => {
          console.log(`  ${idx + 1}. Flight: ${f?.flight?.iata || 'N/A'} | ICAO: ${f?.flight?.icao || 'N/A'} | Number: ${f?.flight?.number || 'N/A'} | Route: ${f?.departure?.iata || '?'}->${f?.arrival?.iata || '?'}`);
        });
        
        // Try multiple matching strategies
        let selectedFlight = null;
        let matchType = 'none';
        
        // Strategy 1: Exact IATA match
        selectedFlight = flights.find((f: any) => {
          const flightIata = f?.flight?.iata || '';
          return flightIata.toUpperCase() === flight.toUpperCase();
        });
        if (selectedFlight) matchType = 'exact-iata';
        
        // Strategy 2: Flight number match
        if (!selectedFlight) {
          selectedFlight = flights.find((f: any) => {
            const flightNum = String(f?.flight?.number || '');
            return flightNum === flightNumber;
          });
          if (selectedFlight) matchType = 'flight-number';
        }
        
        // Strategy 3: IATA contains flight number
        if (!selectedFlight) {
          selectedFlight = flights.find((f: any) => {
            const flightIata = f?.flight?.iata || '';
            return flightIata.includes(flightNumber);
          });
          if (selectedFlight) matchType = 'iata-contains';
        }
        
        // Strategy 4: Use the most recent/relevant flight
        if (!selectedFlight) {
          // Sort by most recent or prefer US routes
          const usFlights = flights.filter((f: any) => {
            const dep = f?.departure?.iata || '';
            const arr = f?.arrival?.iata || '';
            const usAirports = ['JFK', 'LAX', 'ORD', 'DFW', 'ATL', 'LGA', 'EWR', 'MIA', 'LAS', 'PHX', 'SEA', 'SFO', 'BOS', 'DEN'];
            return usAirports.includes(dep) || usAirports.includes(arr);
          });
          
          selectedFlight = usFlights.length > 0 ? usFlights[0] : flights[0];
          matchType = usFlights.length > 0 ? 'us-route-representative' : 'representative';
        }
        
        if (!selectedFlight) {
          continue;
        }
        
        source.success = true;
        
        console.log(`[Flight API] ✅ Match found using strategy: ${matchType}`);
        console.log(`[Flight API] Selected flight: ${selectedFlight?.flight?.iata || 'N/A'} (${selectedFlight?.departure?.iata || '?'} -> ${selectedFlight?.arrival?.iata || '?'})`);
        
        // Extract flight information
        const statusRaw = String(selectedFlight.flight_status || 'scheduled').toLowerCase();
        const statusMap: Record<string, FlightProbe['status']> = {
          scheduled: 'Scheduled',
          active: 'On Time',
          landed: 'On Time',
          cancelled: 'Cancelled',
          incident: 'Delayed',
          diverted: 'Delayed',
          delayed: 'Delayed',
        };
        
        const status = statusMap[statusRaw] || 'Scheduled';
        const depDelay = Number(selectedFlight?.departure?.delay ?? 0);
        const arrDelay = Number(selectedFlight?.arrival?.delay ?? 0);
        const maxDelay = Math.max(depDelay, arrDelay);
        
        const aircraftAgeYears = 8;
        const origin = selectedFlight?.departure?.iata || undefined;
        const destination = selectedFlight?.arrival?.iata || undefined;
        
        console.log(`[Flight API] SUCCESS - ${flight} (${matchType} match)`);
        console.log(`[Flight API] Status=${status}, Route=${origin}->${destination}, Delay=${maxDelay}m`);
        console.log(`[Flight API] Airline: ${selectedFlight?.airline?.name}, Aircraft: ${selectedFlight?.aircraft?.type || 'Unknown'}`);
        
        const flightData = {
          status,
          inboundTailDelayMinutes: isFinite(maxDelay) && maxDelay > 0 ? maxDelay : 0,
          aircraftAgeYears,
          origin,
          destination,
        };
        
        return { ...flightData, source };
        
      } catch (error) {
        console.log(`[Flight API] Strategy "${strategy.name}" failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
        continue;
      }
    }

    // All strategies failed
    source.success = false;
    source.errorMessage = 'No flights found with available API parameters';
    console.log(`[Flight API] Could not find data for ${flight} with free plan limitations`);
    
    const fallbackData = {
      status: 'Scheduled' as const,
      inboundTailDelayMinutes: 10,
      aircraftAgeYears: 8,
    };
    return { ...fallbackData, source };
  }
}

// News/context adapter (Newsdata.io if key present; fallback to mock)
type ContextProbe = {
  strikeRisk: boolean;
  advisories: string[];
  atcProgram: boolean;
};

// Enhanced News adapter with detailed logging and progressive fallback queries
class NewsAdapter {
  constructor(private cfg: MCPConfig) {}

  public async get(airlineOrRouteHint: string, origin?: string, destination?: string): Promise<ContextProbe & { source: DataSource }> {
    const source: DataSource = {
      source: 'NewsData.io',
      apiUsed: false,
      success: false,
      timestamp: new Date().toISOString()
    };

    if (!this.cfg.NEWSDATA_API_KEY || this.cfg.SIMULATION) {
      source.source = 'Mock Data (Simulation)';
      source.success = true;
      source.errorMessage = this.cfg.SIMULATION ? 'Simulation mode enabled' : 'No API key provided';
      
      const mockData = {
        strikeRisk: airlineOrRouteHint.toUpperCase().includes('AA123'),
        advisories: destination === 'LAX' ? [] : ['General advisory for destination.'],
        atcProgram: origin === 'JFK',
      };
      
      console.log(`[News API] Using MOCK data - Strike risk: ${mockData.strikeRisk}, ATC program: ${mockData.atcProgram}`);
      source.rawData = mockData;
      
      return { ...mockData, source };
    }

    // Progressive fallback queries
    const queries = [
      'airline',           // Simplest
      'flight',           // Alternative  
      'travel',           // Backup
      'transportation'    // Last resort
    ];

    source.apiUsed = true;
    
    for (let i = 0; i < queries.length; i++) {
      const query = queries[i];
      const url = `https://newsdata.io/api/1/news?apikey=${this.cfg.NEWSDATA_API_KEY}&q=${encodeURIComponent(
        query
      )}&country=us&language=en&size=5`;

      try {
        console.log(`[News API] Attempt ${i + 1}/${queries.length}: Trying query "${query}"`);
        
        const res = await fetchWithRetry(url, { method: 'GET' }, this.cfg);
        const data: any = await res.json();
        
        // Check for API error response format
        if (data.status === 'error' || data.code) {
          const errorMsg = data.results?.message || data.message || `API Error: ${data.code || 'Unknown'}`;
          console.log(`[News API] Query "${query}" returned error: ${errorMsg}`);
          continue; // Try next query
        }
        
        source.rawData = data;
        source.success = true;
        
        const articles: any[] = Array.isArray(data?.results) ? data.results : [];
        console.log(`[News API] SUCCESS with query "${query}" - Found ${articles.length} articles`);

        if (articles.length === 0) {
          console.log(`[News API] No articles found with "${query}", trying next query...`);
          continue; // Try next query
        }

        const text = articles.map((a) => `${a?.title ?? ''} ${a?.description ?? ''}`.toLowerCase()).join(' ');

        const strikeRisk = text.includes('strike') || text.includes('labor') || text.includes('union');
        const atcProgram = text.includes('delay') || text.includes('cancel') || text.includes('ground');

        const advisories: string[] = [];
        if (text.includes('advisory') || text.includes('alert')) {
          advisories.push('Travel advisories reported in news.');
        }
        
        console.log(`[News API] Analysis - Strike risk: ${strikeRisk}, ATC programs: ${atcProgram}, Advisories: ${advisories.length}`);
        
        return { strikeRisk, advisories, atcProgram, source };
        
      } catch (error) {
        console.log(`[News API] Query "${query}" failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
        if (i === queries.length - 1) {
          // Last attempt failed
          source.success = false;
          source.errorMessage = error instanceof Error ? error.message : 'All query attempts failed';
          console.log(`[News API] All ${queries.length} query attempts failed`);
          
          const fallbackData = { strikeRisk: false, advisories: [], atcProgram: false };
          return { ...fallbackData, source };
        }
        continue; // Try next query
      }
    }

    // If we get here, something unexpected happened
    source.success = false;
    source.errorMessage = 'All query attempts exhausted';
    const fallbackData = { strikeRisk: false, advisories: [], atcProgram: false };
    return { ...fallbackData, source };
  }
}

// Enhanced TSA adapter
class TSAAdapter {
  constructor(private cfg: MCPConfig) {}
  
  public async get(origin?: string): Promise<{ waitMinutes: number; isAboveBaseline: boolean; source: DataSource }> {
    const source: DataSource = {
      source: 'TSA Simulation',
      apiUsed: false,
      success: true,
      timestamp: new Date().toISOString(),
      errorMessage: 'No real TSA API available - using airport-based estimates'
    };

    // Enhanced airport-specific estimates
    const airportWaitTimes: Record<string, number> = {
      'JFK': 35, 'LAX': 40, 'ORD': 30, 'ATL': 32, 'DFW': 28,
      'DEN': 25, 'SFO': 38, 'SEA': 22, 'MIA': 35, 'LAS': 30,
      'BOS': 25, 'LGA': 30, 'EWR': 32, 'IAD': 20, 'DCA': 18
    };
    
    const waitMinutes = airportWaitTimes[origin || ''] || 20;
    const isAboveBaseline = waitMinutes > 20;
    
    console.log(`[TSA API] Airport ${origin || 'Unknown'}: Estimated wait ${waitMinutes}m (${isAboveBaseline ? 'Above' : 'Below'} baseline)`);
    
    source.rawData = { airport: origin, estimatedWait: waitMinutes, baseline: 20 };
    
    return { waitMinutes, isAboveBaseline, source };
  }
}

// -------------------- 4. Risk Engine --------------------

class RiskEngine {
  /**
   * Normalizes inputs and computes the composite disruption risk score.
   * The score reflects both 'hard ops' (weather, ATC) and 'soft context' (policy, labor).
   * @param data The FusedData object.
   * @returns A composite risk score and a concise breakdown.
   */
  public static calculate(data: FusedData): { score: number; breakdown: string[] } {
    let score = 0;
    const weights = {
      inboundTail: 0.3,
      weather: 0.25,
      tsa: 0.1,
      context: 0.35, // Labor/Policy/ATC
    };
    const breakdown: string[] = [];

    // 1. Inbound/Mechanical Risk (Weight: 0.3)
    let inboundRisk = Math.min(data.flight.inboundTailDelayMinutes / 120, 1.0); // Normalize to max 2 hours delay
    if (data.flight.aircraftAgeYears > 15) inboundRisk += 0.1; // Older aircraft penalty
    inboundRisk = Math.min(inboundRisk, 1.0);
    score += inboundRisk * weights.inboundTail;
    breakdown.push(
      `Inbound Ops/Mechanical Risk: ${Math.round(inboundRisk * 100)}% (Tail Delay: ${data.flight.inboundTailDelayMinutes}m)`
    );

    // 2. Weather Risk (Weight: 0.25)
    let weatherFactor = 0;
    if (data.weather.enrouteConvectiveRisk === 'Moderate') weatherFactor = 0.4;
    if (data.weather.enrouteConvectiveRisk === 'High') weatherFactor = 0.8;
    score += weatherFactor * weights.weather;
    breakdown.push(
      `Weather Risk: ${Math.round(weatherFactor * 100)}% (${data.weather.enrouteConvectiveRisk} convective outlook)`
    );

    // 3. Contextual/Policy/ATC Risk (Weight: 0.35)
    let contextRisk = 0;
    if (data.context.strikeRisk) {
      contextRisk += 0.5;
      breakdown.push('High Labor Action Risk.');
    }
    if (data.context.atcProgram) {
      contextRisk += 0.3;
      breakdown.push('Active ATC Program/Ground Stop.');
    }
    if ((data.context.advisories || []).length > 0) {
      contextRisk += 0.2;
      breakdown.push('International/General Travel Advisories Present.');
    }
    score += Math.min(contextRisk, 1.0) * weights.context;

    // 4. Security/TSA Risk (Weight: 0.1)
    let tsaRisk = data.tsa.isAboveBaseline ? data.tsa.waitMinutes / 60 : 0; // Normalize to max 60 min wait
    tsaRisk = Math.min(tsaRisk, 1.0);
    score += tsaRisk * weights.tsa;
    breakdown.push(`TSA/Security Risk: ${Math.round(tsaRisk * 100)}% (${data.tsa.waitMinutes}m wait)`);

    const finalScore = Math.min(score, 1.0); // Clamp score at 1.0
    return { score: finalScore, breakdown };
  }
}

class InteractiveHTMLDashboard {
  static generate(intent: TravelIntent, fusedData: EnhancedFusedData, score: number, breakdown: string[]): string {
    const percentage = Math.round(score * 100);
    const riskLevel = percentage > 60 ? 'HIGH RISK' : percentage > 30 ? 'MODERATE RISK' : 'LOW RISK';
    const riskColor = percentage > 60 ? '#e74c3c' : percentage > 30 ? '#f39c12' : '#27ae60';
    
    // Extract component percentages for charts
    const components = breakdown.map(item => {
      const match = item.match(/(\w+.*?):\s*(\d+)%/);
      return {
        name: match ? match[1].replace(' Risk', '').replace(' Ops/Mechanical', ' Operations') : 'Unknown',
        value: match ? parseInt(match[2]) : 0
      };
    });

    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>✈️ MCP Risk Dashboard - ${intent.flightDesignator || 'Travel Assessment'}</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            color: #2c3e50;
        }
        
        .container {
            max-width: 1400px;
            margin: 0 auto;
            padding: 20px;
        }
        
        .header {
            background: rgba(255, 255, 255, 0.95);
            backdrop-filter: blur(10px);
            padding: 30px;
            border-radius: 20px;
            margin-bottom: 30px;
            text-align: center;
            box-shadow: 0 8px 25px rgba(0, 0, 0, 0.1);
        }
        
        .header h1 {
            font-size: 2.5rem;
            margin-bottom: 10px;
            background: linear-gradient(45deg, #667eea, #764ba2);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }
        
        .flight-info {
            display: flex;
            justify-content: center;
            gap: 30px;
            margin-top: 20px;
            flex-wrap: wrap;
        }
        
        .flight-detail {
            background: rgba(255, 255, 255, 0.7);
            padding: 15px 25px;
            border-radius: 15px;
            font-weight: 600;
        }
        
        .dashboard-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 30px;
            margin-bottom: 30px;
        }
        
        @media (max-width: 768px) {
            .dashboard-grid { grid-template-columns: 1fr; }
        }
        
        .card {
            background: rgba(255, 255, 255, 0.95);
            backdrop-filter: blur(10px);
            border-radius: 20px;
            padding: 30px;
            box-shadow: 0 8px 25px rgba(0, 0, 0, 0.1);
        }
        
        .gauge-container {
            text-align: center;
        }
        
        .gauge-wrapper {
            position: relative;
            width: 300px;
            height: 200px;
            margin: 30px auto;
        }
        
        .gauge {
            width: 300px;
            height: 150px;
            background: conic-gradient(from 180deg, 
                #27ae60 0deg 72deg,
                #f39c12 72deg 126deg, 
                #e74c3c 126deg 180deg);
            border-radius: 150px 150px 0 0;
            position: relative;
            overflow: hidden;
        }
        
        .gauge::before {
            content: '';
            position: absolute;
            top: 30px;
            left: 30px;
            right: 30px;
            bottom: 0;
            background: white;
            border-radius: 120px 120px 0 0;
        }
        
        .needle {
            position: absolute;
            bottom: 0;
            left: 50%;
            width: 4px;
            height: 120px;
            background: linear-gradient(to top, #2c3e50, #34495e);
            transform-origin: bottom center;
            transform: translateX(-50%) rotate(-70deg);
            border-radius: 2px 2px 0 0;
            animation: needleMove 2s ease-out forwards;
            z-index: 10;
        }
        
        @keyframes needleMove {
            from { transform: translateX(-50%) rotate(-90deg); }
            to { transform: translateX(-50%) rotate(${-90 + (percentage * 1.8)}deg); }
        }
        
        .needle::after {
            content: '';
            position: absolute;
            bottom: -8px;
            left: 50%;
            width: 16px;
            height: 16px;
            background: #2c3e50;
            border: 3px solid white;
            border-radius: 50%;
            transform: translateX(-50%);
        }
        
        .gauge-value {
            position: absolute;
            bottom: 40px;
            width: 100%;
            text-align: center;
        }
        
        .percentage {
            font-size: 3rem;
            font-weight: bold;
            color: ${riskColor};
            animation: countUp 2s ease-out forwards;
        }
        
        .risk-label {
            font-size: 1.2rem;
            font-weight: 600;
            color: ${riskColor};
            margin-top: 5px;
        }
        
        @keyframes countUp {
            from { opacity: 0; transform: scale(0.5); }
            to { opacity: 1; transform: scale(1); }
        }
        
        .components-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }
        
        .component-card {
            background: rgba(255, 255, 255, 0.95);
            backdrop-filter: blur(10px);
            border-radius: 15px;
            padding: 20px;
            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.1);
            transition: transform 0.3s ease;
        }
        
        .component-card:hover {
            transform: translateY(-5px);
        }
        
        .component-header {
            display: flex;
            justify-content: between;
            align-items: center;
            margin-bottom: 15px;
        }
        
        .status-icon {
            font-size: 1.5rem;
            margin-right: 10px;
        }
        
        .progress-container {
            background: #ecf0f1;
            height: 8px;
            border-radius: 4px;
            overflow: hidden;
            margin: 10px 0;
        }
        
        .progress-bar {
            height: 100%;
            border-radius: 4px;
            transition: width 2s ease-out;
            animation: progressGrow 2s ease-out forwards;
        }
        
        @keyframes progressGrow {
            from { width: 0; }
        }
        
        .chart-container {
            height: 300px;
            margin-top: 20px;
        }
        
        .data-sources {
            background: rgba(255, 255, 255, 0.95);
            backdrop-filter: blur(10px);
            border-radius: 20px;
            padding: 30px;
            box-shadow: 0 8px 25px rgba(0, 0, 0, 0.1);
        }
        
        .source-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 15px;
            border-bottom: 1px solid #ecf0f1;
            transition: background-color 0.3s ease;
        }
        
        .source-item:hover {
            background-color: rgba(103, 126, 234, 0.1);
            border-radius: 10px;
        }
        
        .source-item:last-child {
            border-bottom: none;
        }
        
        .source-success { color: #27ae60; }
        .source-error { color: #e74c3c; }
        .source-warning { color: #f39c12; }
        
        .error-details {
            font-size: 0.9rem;
            color: #7f8c8d;
            margin-top: 5px;
        }
        
        .refresh-btn {
            position: fixed;
            bottom: 30px;
            right: 30px;
            background: linear-gradient(45deg, #667eea, #764ba2);
            color: white;
            border: none;
            padding: 15px 20px;
            border-radius: 50px;
            font-size: 16px;
            cursor: pointer;
            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
            transition: transform 0.3s ease;
        }
        
        .refresh-btn:hover {
            transform: scale(1.1);
        }
        
        .timestamp {
            text-align: center;
            color: #7f8c8d;
            margin-top: 20px;
            font-size: 0.9rem;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>✈️ MCP Risk Dashboard</h1>
            <div class="flight-info">
                <div class="flight-detail">
                    <div>Flight: <strong>${intent.flightDesignator || 'N/A'}</strong></div>
                </div>
                <div class="flight-detail">
                    <div>Route: <strong>${intent.originAirport || '?'} → ${intent.destinationAirport || '?'}</strong></div>
                </div>
                <div class="flight-detail">
                    <div>Date: <strong>${intent.dateOfTravel}</strong></div>
                </div>
                <div class="flight-detail">
                    <div>Action: <strong>${intent.action.replace('_', ' ').toUpperCase()}</strong></div>
                </div>
            </div>
        </div>
        
        <div class="dashboard-grid">
            <div class="card gauge-container">
                <h2>Overall Disruption Risk</h2>
                <div class="gauge-wrapper">
                    <div class="gauge">
                        <div class="needle"></div>
                    </div>
                    <div class="gauge-value">
                        <div class="percentage" id="riskPercentage">0%</div>
                        <div class="risk-label">${riskLevel}</div>
                    </div>
                </div>
            </div>
            
            <div class="card">
                <h2>Risk Components Breakdown</h2>
                <div class="chart-container">
                    <canvas id="riskChart"></canvas>
                </div>
            </div>
        </div>
        
        <div class="components-grid">
            ${this.generateComponentCards(components)}
        </div>
        
        <div class="data-sources">
            <h2>📊 Data Sources & Validation</h2>
            ${this.generateDataSourceStatus(fusedData)}
        </div>
        
        <div class="timestamp">
            Last updated: ${new Date().toLocaleString()}
        </div>
    </div>
    
    <button class="refresh-btn" onclick="location.reload()">
        🔄 Refresh
    </button>
    
    <script>
        // Animate percentage counter
        function animateCounter() {
            const counter = document.getElementById('riskPercentage');
            const target = ${percentage};
            let current = 0;
            const increment = target / 60; // 60 frames for smooth animation
            
            const timer = setInterval(() => {
                current += increment;
                if (current >= target) {
                    current = target;
                    clearInterval(timer);
                }
                counter.textContent = Math.round(current) + '%';
            }, 30);
        }
        
        // Initialize chart
        function initChart() {
            const ctx = document.getElementById('riskChart').getContext('2d');
            new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: ${JSON.stringify(components.map(c => c.name))},
                    datasets: [{
                        data: ${JSON.stringify(components.map(c => c.value))},
                        backgroundColor: [
                            '#3498db',
                            '#e74c3c', 
                            '#f39c12',
                            '#27ae60',
                            '#9b59b6'
                        ],
                        borderWidth: 0
                    }]
                },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    plugins: {
                        legend: {
                            position: 'bottom',
                            labels: {
                                padding: 20,
                                usePointStyle: true
                            }
                        },
                        tooltip: {
                            callbacks: {
                                label: function(context) {
                                    return context.label + ': ' + context.parsed + '%';
                                }
                            }
                        }
                    },
                    animation: {
                        animateRotate: true,
                        duration: 2000
                    }
                }
            });
        }
        
        // Initialize everything when page loads
        window.addEventListener('load', () => {
            setTimeout(animateCounter, 500);
            setTimeout(initChart, 1000);
        });
        
        // Add some interactive hover effects
        document.querySelectorAll('.component-card').forEach(card => {
            card.addEventListener('mouseenter', () => {
                card.style.background = 'rgba(103, 126, 234, 0.1)';
            });
            card.addEventListener('mouseleave', () => {
                card.style.background = 'rgba(255, 255, 255, 0.95)';
            });
        });
    </script>
</body>
</html>`;
  }

  private static generateComponentCards(components: Array<{name: string, value: number}>): string {
    return components.map(component => {
      const color = component.value > 40 ? '#e74c3c' : component.value > 20 ? '#f39c12' : '#27ae60';
      const icon = component.value > 40 ? '🔴' : component.value > 20 ? '🟡' : '🟢';
      
      return `
        <div class="component-card">
            <div class="component-header">
                <span class="status-icon">${icon}</span>
                <h3>${component.name}</h3>
                <strong>${component.value}%</strong>
            </div>
            <div class="progress-container">
                <div class="progress-bar" style="width: ${component.value}%; background-color: ${color};"></div>
            </div>
        </div>
      `;
    }).join('');
  }

  private static generateDataSourceStatus(fusedData: EnhancedFusedData): string {
    return Object.entries(fusedData.dataSources).map(([key, source]) => {
      const statusClass = source.success ? 'source-success' : 'source-error';
      const statusIcon = source.success ? '✅' : '❌';
      const apiType = source.apiUsed ? 'REAL API' : 'SIMULATION';
      
      return `
        <div class="source-item">
            <div>
                <strong>${statusIcon} ${key.toUpperCase()}</strong>
                <div><strong>Source:</strong> ${source.source}</div>
                <div><strong>Type:</strong> <span class="${statusClass}">${apiType}</span></div>
                ${source.errorMessage ? `<div class="error-details">Error: ${source.errorMessage}</div>` : ''}
            </div>
            <div style="font-size: 0.8rem; color: #7f8c8d;">
                ${new Date(source.timestamp).toLocaleTimeString()}
            </div>
        </div>
      `;
    }).join('');
  }
}

// -------------------- 5. MCP Server Core --------------------

class MCP_Server {
  private readonly GEMINI_API_URL =
    'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key=';

  private readonly cfg: MCPConfig;

  private readonly weatherAdapter: WeatherAdapter;
  private readonly flightAdapter: FlightAdapter;
  private readonly newsAdapter: NewsAdapter;
  private readonly tsaAdapter: TSAAdapter;

  constructor(configOverrides?: Partial<MCPConfig>) {
    this.cfg = { ...DefaultConfig, ...(configOverrides || {}) };

    this.weatherAdapter = new WeatherAdapter(this.cfg);
    this.flightAdapter = new FlightAdapter(this.cfg);
    this.newsAdapter = new NewsAdapter(this.cfg);
    this.tsaAdapter = new TSAAdapter(this.cfg);

    console.log('MCP Server Initialized. Ready to process travel context queries.');
  }

  /**
   * [SIMULATED] Calls the Gemini API to transform a natural language prompt into a structured JSON intent.
   * This is the "Prompt Gateway" component.
   */
  private async getIntent(prompt: string): Promise<TravelIntent> {
    console.log(`\n[Prompt Gateway] Interpreting prompt: "${prompt}"`);

    // Use lightweight extraction + heuristics to sharpen "tomorrow/today" and route parsing.
    const flightDesignator = parseFlightDesignator(prompt);
    const dateOfTravel = inferDateFromPrompt(prompt);
    const { origin, destination } = parseIataPair(prompt);

    let action: TravelIntent['action'] = 'risk_check';
    const p = prompt.toLowerCase();
    if (p.includes('resilien')) action = 'resilience_check';
    if (p.includes('rebook')) action = 'rebook_options'; // If explicitly asking for rebooking options

    const requestedBackups: string[] = [];
    if (p.includes('hotel')) requestedBackups.push('hotel');
    if (p.includes('rebook')) requestedBackups.push('rebooking');
    if (p.includes('car')) requestedBackups.push('car');

    const intent: TravelIntent = {
      id: crypto.randomUUID(),
      action,
      flightDesignator,
      originAirport: origin,
      destinationAirport: destination,
      dateOfTravel,
      riskThreshold: 0.6,
      requestedBackups: requestedBackups.length ? requestedBackups : ['rebooking'],
    };

    console.log(`[Prompt Gateway] Intent resolved successfully.`);
    return intent;
  }

  /**
   * Calls provider adapters (Aviationstack, NOAA/WeatherAPI, Newsdata) and fuses results.
   * Falls back gracefully if keys are missing or calls fail.
   */
  private async fetchAndFuseData(intent: TravelIntent): Promise<EnhancedFusedData> {
  console.log(`\n[Data Fusion] Fetching data for action: ${intent.action}`);
  console.log(`[Data Fusion] API Keys configured: Weather=${!!this.cfg.WEATHER_API_KEY}, Flight=${!!this.cfg.AVIATIONSTACK_API_KEY}, News=${!!this.cfg.NEWSDATA_API_KEY}`);
  console.log(`[Data Fusion] Simulation mode: ${this.cfg.SIMULATION}`);

  // 1) Flight data (if flightDesignator present, it takes precedence to fill route)
    let flightProbeResult: FlightProbe & { source: DataSource } = {
  status: 'Scheduled',
  inboundTailDelayMinutes: 10,
  aircraftAgeYears: 8,
  origin: undefined,
  destination: undefined,
  source: {
    source: 'Default',
    apiUsed: false,
    success: true,
    timestamp: new Date().toISOString()
  }
};

  if (intent.flightDesignator) {
    flightProbeResult = await this.flightAdapter.getByDesignator(intent.flightDesignator, intent.dateOfTravel);
    // If origin/dest missing in intent, adopt from probe
    if (!intent.originAirport && flightProbeResult.origin) {
      intent.originAirport = flightProbeResult.origin;
    }
    if (!intent.destinationAirport && flightProbeResult.destination) {
      intent.destinationAirport = flightProbeResult.destination;
    }
  }

  // 2) Weather (use origin airport if available; otherwise destination)
  const wxAirport = intent.originAirport || intent.destinationAirport;
  const weatherResult = await this.weatherAdapter.get(wxAirport);

  // 3) TSA (origin-sided)
  const tsaResult = await this.tsaAdapter.get(intent.originAirport);

  // 4) News/context (airline hint: flightDesignator's prefix)
  const airlineOrRoute =
    intent.flightDesignator?.slice(0, 2) ||
    (intent.originAirport && intent.destinationAirport
      ? `${intent.originAirport}-${intent.destinationAirport}`
      : 'general');

  const newsResult = await this.newsAdapter.get(airlineOrRoute, intent.originAirport, intent.destinationAirport);

  const fused: EnhancedFusedData = {
    flight: {
      status: flightProbeResult.status,
      inboundTailDelayMinutes: flightProbeResult.inboundTailDelayMinutes,
      aircraftAgeYears: flightProbeResult.aircraftAgeYears,
    },
    weather: {
      enrouteConvectiveRisk: weatherResult.enrouteConvectiveRisk,
      metar: weatherResult.metar,
    },
    tsa: {
      waitMinutes: tsaResult.waitMinutes,
      isAboveBaseline: tsaResult.isAboveBaseline,
    },
    context: {
      strikeRisk: newsResult.strikeRisk,
      advisories: newsResult.advisories || [],
      atcProgram: newsResult.atcProgram,
    },
    dataSources: {
      flight: flightProbeResult.source,
      weather: weatherResult.source,
      news: newsResult.source,
      tsa: tsaResult.source
    }
  };

  console.log('[Data Fusion] Data fusion complete. Ready for Risk Engine.');
  return fused;
}

  /**
   * Main entry point for processing a user's prompt.
   */
  public async processQuery(prompt: string): Promise<void> {
    try {
      // 1. Prompt Gateway: Get Structured Intent
      const intent = await this.getIntent(prompt);

      // 2. Data Fusion: Fetch all signals
      const fusedData: EnhancedFusedData = await this.fetchAndFuseData(intent);

      // 3. Risk Engine: Calculate composite score
      const { score, breakdown } = RiskEngine.calculate(fusedData);

      // Generate Interactive HTML Dashboard
      const htmlDashboard = InteractiveHTMLDashboard.generate(intent, fusedData, score, breakdown);
      const reportPath = path.join(process.cwd(), `risk_dashboard_${intent.id.substring(0, 8)}.html`);
      fs.writeFileSync(reportPath, htmlDashboard);

      // Auto-open in browser (optional)
      const open = async (url: string) => {
      const { exec } = require('child_process');
      const platform = process.platform;
    
      let command: string;
      if (platform === 'darwin') command = `open "${url}"`;
      else if (platform === 'win32') command = `start "" "${url}"`;
      else command = `xdg-open "${url}"`;
    
    exec(command);
    };

      // 4. Output Generation (Concise Brief)
      console.log('\n======================================================');
      console.log(`\t\t\tMCP RISK BRIEF`);
      console.log('======================================================');
      console.log(`Query ID: ${intent.id} | Action: ${intent.action}`);

      const travelContext =
        intent.flightDesignator ||
        (intent.originAirport && intent.destinationAirport
          ? `${intent.originAirport} -> ${intent.destinationAirport}`
          : 'Unknown route');

      console.log(`Travel Context: ${travelContext} on ${intent.dateOfTravel}`);
      console.log('------------------------------------------------------');
      console.log(`COMPOSITE DISRUPTION RISK SCORE: ${Math.round(score * 100)}%`);

            // DATA SOURCES SECTION
        console.log('\n[DATA SOURCES & VALIDATION]');
        Object.entries(fusedData.dataSources).forEach(([key, source]) => {
        const status = source.success ? '✅' : '❌';
        const apiStatus = source.apiUsed ? 'REAL API' : 'SIMULATION';
        console.log(`  ${status} ${key.toUpperCase()}: ${source.source} (${apiStatus})`);
        if (!source.success && source.errorMessage) {
            console.log(`     └─ Error: ${source.errorMessage}`);
        }
        if (source.success && key === 'weather' && fusedData.weather.metar) {
            console.log(`     └─ METAR: ${fusedData.weather.metar.substring(0, 60)}...`);
        }
        });

      console.log(`\n[TOP RISKS]`);
      breakdown.forEach((line) => console.log(`  - ${line}`));

      // 5. Action Planning / Mitigation
      if (score >= intent.riskThreshold) {
        console.log('\n[ACTION TRIGGERED]');
        console.log(`Risk (${Math.round(score * 100)}%) exceeds threshold (${Math.round(intent.riskThreshold * 100)}%).`);
        console.log(`Proposing / Executing Backups: ${intent.requestedBackups.join(', ')}.`);

        // Simulated mitigation
        if (intent.requestedBackups.includes('hotel')) {
          const airport = intent.originAirport || 'origin';
          console.log(`  - Hotel Hold Executed: Found 3-star hotel near ${airport} for $199/night.`);
        }
        if (intent.requestedBackups.includes('rebooking')) {
          console.log(
            `  - Rebooking Advisory: Alternate flight UA456 via IAH identified (1hr 30m layover, 40% less risk).`
          );
        }
        if (intent.requestedBackups.includes('car')) {
          console.log(`  - Car Rental Option: Compact car hold near airport for $58/day.`);
        }
      } else {
        console.log('\n[STATUS] Below action threshold. Monitoring continues.');
      }
      console.log('\n[INTERACTIVE DASHBOARD]');
        console.log(`📊 Interactive HTML dashboard generated: ${reportPath}`);
        console.log(`🌐 Opening in browser...`);

        // Auto-open the dashboard
        setTimeout(() => {
        open(`file://${reportPath}`);
        }, 1000);

      console.log('======================================================');
    } catch (error) {
      console.error('[MCP Server Error]', error);
    }
  }
}

// -------------------- 6. Example Usage --------------------
// Now using environment variables from .env file
const mcpServer = new MCP_Server();

// -------------------- 7. Main Function --------------------
async function main() {
  await testAPIKeys();
  
  console.log('\n=== Single Flight Test ===');
  await mcpServer.processQuery('Check AA1052 status today from DFW to TYS. Any weather issues?');
}

// Run the main function
main().catch(console.error);